name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          echo "Pinging backend service..."
          curl -s https://scrum-dashboard-backend.onrender.com/ping
          echo "\nPing completed at $(date)" 
